// <auto-generated />
namespace Bank.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class transaction_type : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(transaction_type));
        
        string IMigrationMetadata.Id
        {
            get { return "201411072109587_transaction_type"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
