// <auto-generated />
namespace Bank.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class transaction_typeString : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(transaction_typeString));
        
        string IMigrationMetadata.Id
        {
            get { return "201411072217404_transaction_typeString"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
